#ifndef WEB_CONTENT_H
#define WEB_CONTENT_H

// Conteúdo HTML embutido da interface web
const char html_content[] = 
"<!DOCTYPE html>\n"
"<html lang=\"pt-BR\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>iBag - Controle de Temperatura</title>\n"
"    <style>\n"
"        * { margin: 0; padding: 0; box-sizing: border-box; }\n"
"        :root {\n"
"            --primary-color: #2563eb;\n"
"            --success-color: #10b981;\n"
"            --warning-color: #f59e0b;\n"
"            --danger-color: #ef4444;\n"
"            --bg-color: #f8fafc;\n"
"            --card-bg: #ffffff;\n"
"            --text-primary: #1e293b;\n"
"            --text-secondary: #64748b;\n"
"            --border-color: #e2e8f0;\n"
"        }\n"
"        body {\n"
"            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\n"
"            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n"
"            min-height: 100vh;\n"
"            padding: 20px;\n"
"            color: var(--text-primary);\n"
"        }\n"
"        .container { max-width: 800px; margin: 0 auto; }\n"
"        header {\n"
"            text-align: center;\n"
"            color: white;\n"
"            margin-bottom: 30px;\n"
"            padding: 20px;\n"
"        }\n"
"        header h1 { font-size: 3rem; margin-bottom: 10px; text-shadow: 2px 2px 4px rgba(0,0,0,0.2); }\n"
"        header p { font-size: 1.2rem; opacity: 0.9; }\n"
"        section {\n"
"            background: var(--card-bg);\n"
"            border-radius: 16px;\n"
"            padding: 24px;\n"
"            margin-bottom: 20px;\n"
"            box-shadow: 0 10px 15px -3px rgba(0,0,0,0.1);\n"
"        }\n"
"        section h2 { font-size: 1.5rem; margin-bottom: 20px; }\n"
"        .status-badge {\n"
"            padding: 8px 16px;\n"
"            border-radius: 20px;\n"
"            font-weight: 600;\n"
"            background-color: #d1fae5;\n"
"            color: var(--success-color);\n"
"            display: inline-block;\n"
"            margin-bottom: 16px;\n"
"        }\n"
"        .config-group { display: flex; flex-direction: column; gap: 20px; margin-bottom: 24px; }\n"
"        .input-group { display: flex; flex-direction: column; gap: 8px; }\n"
"        .input-group label { font-weight: 600; display: flex; align-items: center; gap: 8px; }\n"
"        .input-wrapper {\n"
"            display: flex;\n"
"            align-items: center;\n"
"            gap: 8px;\n"
"            background: var(--bg-color);\n"
"            border: 2px solid var(--border-color);\n"
"            border-radius: 8px;\n"
"            padding: 4px 12px;\n"
"        }\n"
"        .input-wrapper input {\n"
"            flex: 1;\n"
"            border: none;\n"
"            background: transparent;\n"
"            font-size: 1.1rem;\n"
"            padding: 8px;\n"
"            outline: none;\n"
"        }\n"
"        .unit { font-weight: 600; color: var(--text-secondary); }\n"
"        .btn {\n"
"            display: inline-flex;\n"
"            align-items: center;\n"
"            justify-content: center;\n"
"            gap: 8px;\n"
"            padding: 12px 24px;\n"
"            border: none;\n"
"            border-radius: 8px;\n"
"            font-size: 1rem;\n"
"            font-weight: 600;\n"
"            cursor: pointer;\n"
"            width: 100%;\n"
"            transition: all 0.3s ease;\n"
"        }\n"
"        .btn:hover { transform: translateY(-2px); }\n"
"        .btn-success { background-color: var(--success-color); color: white; }\n"
"        .btn-info { background-color: #06b6d4; color: white; }\n"
"        .btn-warning { background-color: var(--warning-color); color: white; margin-top: 12px; }\n"
"        .status-display { margin-top: 20px; }\n"
"        .status-card {\n"
"            background: var(--bg-color);\n"
"            border-radius: 12px;\n"
"            padding: 20px;\n"
"            margin-bottom: 16px;\n"
"        }\n"
"        .temp-display { display: flex; flex-direction: column; gap: 12px; }\n"
"        .temp-item {\n"
"            display: flex;\n"
"            align-items: center;\n"
"            gap: 12px;\n"
"            padding: 12px;\n"
"            background: white;\n"
"            border-radius: 8px;\n"
"            border: 2px solid var(--border-color);\n"
"        }\n"
"        .temp-item .value {\n"
"            margin-left: auto;\n"
"            font-size: 1.3rem;\n"
"            font-weight: 700;\n"
"            color: var(--primary-color);\n"
"        }\n"
"        .shake-status {\n"
"            display: flex;\n"
"            align-items: center;\n"
"            gap: 12px;\n"
"            padding: 16px;\n"
"            background: white;\n"
"            border-radius: 8px;\n"
"            border: 2px solid var(--border-color);\n"
"            font-size: 1.1rem;\n"
"            font-weight: 600;\n"
"        }\n"
"        .shake-status.shaken { border-color: var(--warning-color); background-color: #fef3c7; }\n"
"        .shake-status.stable { border-color: var(--success-color); background-color: #d1fae5; }\n"
"        .hidden { display: none !important; }\n"
"        .popup {\n"
"            position: fixed;\n"
"            top: 0; left: 0;\n"
"            width: 100%; height: 100%;\n"
"            background-color: rgba(0,0,0,0.5);\n"
"            display: flex;\n"
"            align-items: center;\n"
"            justify-content: center;\n"
"            z-index: 1000;\n"
"        }\n"
"        .popup-content {\n"
"            background: white;\n"
"            border-radius: 16px;\n"
"            padding: 32px;\n"
"            text-align: center;\n"
"            max-width: 400px;\n"
"        }\n"
"        .popup-icon { font-size: 4rem; margin-bottom: 16px; }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class=\"container\">\n"
"        <header>\n"
"            <h1>🎒 iBag</h1>\n"
"            <p>Sistema de Controle de Temperatura</p>\n"
"        </header>\n"
"        <section>\n"
"            <h2>Configurações de Temperatura</h2>\n"
"            <div class=\"config-group\">\n"
"                <div class=\"input-group\">\n"
"                    <label><span>🔥</span> Temperatura do Aquecedor</label>\n"
"                    <div class=\"input-wrapper\">\n"
"                        <input type=\"number\" id=\"heaterTemp\" min=\"-10\" max=\"100\" step=\"0.5\" value=\"25\">\n"
"                        <span class=\"unit\">°C</span>\n"
"                    </div>\n"
"                </div>\n"
"                <div class=\"input-group\">\n"
"                    <label><span>❄️</span> Temperatura do Congelador</label>\n"
"                    <div class=\"input-wrapper\">\n"
"                        <input type=\"number\" id=\"freezerTemp\" min=\"-50\" max=\"20\" step=\"0.5\" value=\"24\">\n"
"                        <span class=\"unit\">°C</span>\n"
"                    </div>\n"
"                </div>\n"
"            </div>\n"
"            <button class=\"btn btn-success\" onclick=\"sendConfig()\">📤 Enviar Configurações</button>\n"
"        </section>\n"
"        <section>\n"
"            <h2>Status do Sistema</h2>\n"
"            <button class=\"btn btn-info\" onclick=\"checkStatus()\">🔍 Verificar Status da Comida</button>\n"
"            <div id=\"statusDisplay\" class=\"status-display hidden\">\n"
"                <div class=\"status-card\">\n"
"                    <h3>Temperaturas Atuais</h3>\n"
"                    <div class=\"temp-display\">\n"
"                        <div class=\"temp-item\">\n"
"                            <span>🔥</span>\n"
"                            <span>Aquecedor:</span>\n"
"                            <span id=\"currentHot\" class=\"value\">-- °C</span>\n"
"                        </div>\n"
"                        <div class=\"temp-item\">\n"
"                            <span>❄️</span>\n"
"                            <span>Congelador:</span>\n"
"                            <span id=\"currentCold\" class=\"value\">-- °C</span>\n"
"                        </div>\n"
"                    </div>\n"
"                </div>\n"
"                <div class=\"status-card\">\n"
"                    <h3>Estado da Comida</h3>\n"
"                    <div id=\"shakeStatus\" class=\"shake-status\"></div>\n"
"                    <button id=\"resetShakeBtn\" class=\"btn btn-warning hidden\" onclick=\"resetShake()\">🔄 Resetar Estado</button>\n"
"                </div>\n"
"            </div>\n"
"        </section>\n"
"    </div>\n"
"    <div id=\"popup\" class=\"popup hidden\">\n"
"        <div class=\"popup-content\">\n"
"            <span class=\"popup-icon\" id=\"popupIcon\">✅</span>\n"
"            <h3 id=\"popupTitle\">Sucesso!</h3>\n"
"            <p id=\"popupMessage\">Operação concluída</p>\n"
"            <button class=\"btn btn-success\" onclick=\"closePopup()\">OK</button>\n"
"        </div>\n"
"    </div>\n"
"    <script>\n"
"        function showPopup(icon, title, msg) {\n"
"            document.getElementById('popupIcon').textContent = icon;\n"
"            document.getElementById('popupTitle').textContent = title;\n"
"            document.getElementById('popupMessage').textContent = msg;\n"
"            document.getElementById('popup').classList.remove('hidden');\n"
"        }\n"
"        function closePopup() {\n"
"            document.getElementById('popup').classList.add('hidden');\n"
"        }\n"
"        async function sendConfig() {\n"
"            const heater = document.getElementById('heaterTemp').value;\n"
"            const freezer = document.getElementById('freezerTemp').value;\n"
"            try {\n"
"                const controller = new AbortController();\n"
"                const timeoutId = setTimeout(() => controller.abort(), 5000);\n"
"                const resp = await fetch('/api/config', {\n"
"                    method: 'POST',\n"
"                    headers: {'Content-Type': 'application/json'},\n"
"                    body: JSON.stringify({heater: parseFloat(heater), freezer: parseFloat(freezer)}),\n"
"                    signal: controller.signal\n"
"                });\n"
"                clearTimeout(timeoutId);\n"
"                const data = await resp.json();\n"
"                if(data.status === 'ok') {\n"
"                    showPopup('✅', 'Sucesso!', 'Configurações atualizadas!');\n"
"                } else {\n"
"                    showPopup('❌', 'Erro', 'Falha ao atualizar');\n"
"                }\n"
"            } catch(e) {\n"
"                console.log('Erro:', e);\n"
"                showPopup('❌', 'Erro', 'Falha na comunicação: ' + e.message);\n"
"            }\n"
"        }\n"
"        async function checkStatus() {\n"
"            try {\n"
"                const controller = new AbortController();\n"
"                const timeoutId = setTimeout(() => controller.abort(), 5000);\n"
"                const resp = await fetch('/api/status', {\n"
"                    signal: controller.signal\n"
"                });\n"
"                clearTimeout(timeoutId);\n"
"                const data = await resp.json();\n"
"                document.getElementById('currentHot').textContent = data.heater.toFixed(1) + ' °C';\n"
"                document.getElementById('currentCold').textContent = data.freezer.toFixed(1) + ' °C';\n"
"                const shakeDiv = document.getElementById('shakeStatus');\n"
"                const resetBtn = document.getElementById('resetShakeBtn');\n"
"                if(data.shaken) {\n"
"                    shakeDiv.className = 'shake-status shaken';\n"
"                    shakeDiv.textContent = '⚠️ Comida foi Balançada!';\n"
"                    resetBtn.classList.remove('hidden');\n"
"                } else {\n"
"                    shakeDiv.className = 'shake-status stable';\n"
"                    shakeDiv.textContent = '✅ Comida Estável';\n"
"                    resetBtn.classList.add('hidden');\n"
"                }\n"
"                document.getElementById('statusDisplay').classList.remove('hidden');\n"
"            } catch(e) {\n"
"                console.log('Erro ao verificar status:', e);\n"
"                showPopup('❌', 'Erro', 'Falha ao verificar status: ' + e.message);\n"
"            }\n"
"        }\n"
"        let isCalibrating = false;\n"
"        async function resetShake() {\n"
"            // Mostrar popup informativo ANTES de enviar requisição\n"
"            showPopup('⏱️', 'Recalibrando Sensor', 'O sistema será recalibrado por 10 segundos. NÃO MOVA O DISPOSITIVO! Aguarde...');\n"
"            \n"
"            // Desabilitar auto-refresh durante calibração\n"
"            isCalibrating = true;\n"
"            \n"
"            // Aguardar um momento para o usuário ler a mensagem\n"
"            await new Promise(resolve => setTimeout(resolve, 1000));\n"
"            \n"
"            try {\n"
"                const controller = new AbortController();\n"
"                const timeoutId = setTimeout(() => controller.abort(), 15000);\n"
"                const resp = await fetch('/api/reset', {\n"
"                    method: 'POST',\n"
"                    signal: controller.signal\n"
"                });\n"
"                clearTimeout(timeoutId);\n"
"                const data = await resp.json();\n"
"                if(data.status === 'ok') {\n"
"                    isCalibrating = false;\n"
"                    showPopup('✅', 'Resetado!', 'Estado balançado foi resetado e sensor recalibrado!');\n"
"                    setTimeout(() => checkStatus(), 500);\n"
"                }\n"
"            } catch(e) {\n"
"                // Se der timeout/erro, assumir que funcionou (servidor ocupado calibrando)\n"
"                console.log('Timeout esperado durante calibração:', e);\n"
"                isCalibrating = false;\n"
"                showPopup('✅', 'Resetado!', 'Estado balançado foi resetado e sensor recalibrado!');\n"
"                setTimeout(() => checkStatus(), 500);\n"
"            }\n"
"        }\n"
"        // Auto-atualizar status a cada 5 segundos se o display estiver visível\n"
"        setInterval(() => {\n"
"            if(!isCalibrating && !document.getElementById('statusDisplay').classList.contains('hidden')) {\n"
"                checkStatus();\n"
"            }\n"
"        }, 5000);\n"
"    </script>\n"
"</body>\n"
"</html>";

#endif // WEB_CONTENT_H
